[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "github_actions"
version = "0.0.1"

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
dev = ["pytest"]
